//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liz.DoAn.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LizSetting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LizSetting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Liz.DoAn.Resource.LizSetting", typeof(LizSetting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAIL_BCC {
            get {
                return ResourceManager.GetString("MAIL_BCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AEON Thông báo.
        /// </summary>
        internal static string MAIL_BODY {
            get {
                return ResourceManager.GetString("MAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào {_Tên_},&lt;br /&gt;&lt;br /&gt;Bên dưới là tài khoản và mật khẩu của bạn.&lt;br /&gt;&lt;br /&gt;-	Email: {_Email_}&lt;br /&gt;-	Tài khoản: {_Tài khoản_}&lt;br /&gt;-	Mật khẩu: {_Mật khẩu_}&lt;br /&gt;&lt;br /&gt;Mọi thắc mắc xin vui lòng liên hệ bộ phận quản trị của công ty để được giúp đỡ.&lt;br /&gt;&lt;br /&gt;Cám ơn..
        /// </summary>
        internal static string MAIL_BODY_MATKHAUMOI {
            get {
                return ResourceManager.GetString("MAIL_BODY_MATKHAUMOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào {_Tên_},&lt;br /&gt;&lt;br /&gt;Bên dưới là tài khoản và mật khẩu của bạn.&lt;br /&gt;Hãy tải ứng dụng AEON để sử dụng nhé!&lt;br /&gt;&lt;br /&gt;-	Email: {_Email_}&lt;br /&gt;-	Tài khoản: {_Tài khoản_}&lt;br /&gt;-	Mật khẩu: {_Mật khẩu_}&lt;br /&gt;&lt;br /&gt;Mọi thắc mắc xin vui lòng liên hệ bộ phận quản trị của công ty để được giúp đỡ.&lt;br /&gt;&lt;br /&gt;Cám ơn..
        /// </summary>
        internal static string MAIL_BODY_TAIKHOANKHACHHANG {
            get {
                return ResourceManager.GetString("MAIL_BODY_TAIKHOANKHACHHANG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MAIL_CC {
            get {
                return ResourceManager.GetString("MAIL_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tuanphuc.biz4@gmail.com.
        /// </summary>
        internal static string MAIL_FROM {
            get {
                return ResourceManager.GetString("MAIL_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUE.
        /// </summary>
        internal static string MAIL_IS_HTML_BODY {
            get {
                return ResourceManager.GetString("MAIL_IS_HTML_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;width: 700px; padding: 20px 20px 20px 20px&quot;&gt;
        ///	&lt;table style=&quot;width: 100%; border: solid 1px #176081&quot; cellpadding=&quot;4&quot; cellspacing=&quot;4&quot;&gt;
        ///		&lt;tr&gt;
        ///			&lt;td style=&quot;color: #FFFFFF; background-color: #0070B9; padding: 10px; font-size: 12px;
        ///				font-weight: bold; font-family: Arial&quot;&gt;
        ///				{_title_}
        ///			&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///		&lt;tr&gt;
        ///			&lt;td style=&quot;color: #000000; padding: 10px; font-size: 12px; font-family: Arial&quot;&gt;
        ///				{_body_}
        ///			&lt;/td&gt;
        ///		&lt;/tr&gt;
        ///		&lt;tr&gt;
        ///			&lt;td style=&quot;color: #FFFFFF; background-color: #9D9FA2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MAIL_MASTER_TEMPLATE {
            get {
                return ResourceManager.GetString("MAIL_MASTER_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AEON.
        /// </summary>
        internal static string MAIL_SENDER {
            get {
                return ResourceManager.GetString("MAIL_SENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AEON Thông báo.
        /// </summary>
        internal static string MAIL_SUBJECT {
            get {
                return ResourceManager.GetString("MAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bên dưới là thông tin tài khoản của bạn.
        /// </summary>
        internal static string MAIL_SUBJECT_TAIKHOANMOI {
            get {
                return ResourceManager.GetString("MAIL_SUBJECT_TAIKHOANMOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tuanphuc.biz4@gmail.com.
        /// </summary>
        internal static string MAIL_TO {
            get {
                return ResourceManager.GetString("MAIL_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33615755.
        /// </summary>
        internal static string PASSWORD_EMAIL {
            get {
                return ResourceManager.GetString("PASSWORD_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tuanphuc.biz4@gmail.com.
        /// </summary>
        internal static string USER_EMAIL {
            get {
                return ResourceManager.GetString("USER_EMAIL", resourceCulture);
            }
        }
    }
}
